FROM ubuntu:22.04
ENV DEBIAN_FRONTEND="noninteractive" \
    FSLDIR="/opt/fsl-6.0.7.1" \
    PATH="/opt/fsl-6.0.7.1/bin:/opt/ants-2.5.4/bin:$PATH" \
    FSLOUTPUTTYPE="NIFTI_GZ" \
    FSLMULTIFILEQUIT="TRUE" \
    FSLTCLSH="$FSLDIR/bin/fsltclsh" \
    FSLWISH="$FSLDIR/bin/fslwish" \
    FSLLOCKDIR="" \
    FSLMACHINELIST="" \
    FSLREMOTECALL="" \
    FSLGECUDAQ="cuda.q"

# Set up Flywheel environment
ENV FLYWHEEL="/flywheel/v0"
RUN mkdir -p ${FLYWHEEL}

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    bc \
    binutils \
    bsdmainutils \
    bzip2 \
    ca-certificates \
    curl \
    dc \
    dcm2niix \
    file \
    gnupg \
    jq \
    libc6-amd64-cross \
    libfontconfig1 \
    libfreetype6 \
    libgl1-mesa-dev \
    libgl1-mesa-dri \
    libglu1-mesa-dev \
    libice6 \
    libopenblas-base \
    libtinfo6 \
    libxcursor1 \
    libxft2 \
    libxinerama1 \
    libxrandr2 \
    libxrender1 \
    libxt6 \
    lsb-release \
    nano \
    netbase \
    python3 \
    python3-pip \
    sudo \
    unzip \
    wget \
    zip && \
    apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV ANTSPATH="/opt/ants-2.5.4/bin" \
    PATH="$ANTSPATH:$PATH"
RUN mkdir /opt/ants && \
    curl -fsSL https://github.com/ANTsX/ANTs/releases/download/v2.5.4/ants-2.5.4-ubuntu-22.04-X64-gcc.zip -o ants.zip && \
    unzip ants.zip -d /opt && \
    rm ants.zip

# Install FSL 6.0.7.1 using fslinstaller.py
RUN curl -fsSL https://fsl.fmrib.ox.ac.uk/fsldownloads/fslconda/releases/fslinstaller.py | \
    python3 - -d /opt/fsl-6.0.7.1 -V 6.0.7.1 && \
    rm -rf /opt/fsl-6.0.7.1/doc /opt/fsl-6.0.7.1/data

# Install required Python packages
RUN pip3 install --no-cache-dir \
    numpy \
    pandas \
    matplotlib \
    nilearn \
    scipy \
    nibabel \
    jinja2 \
    flywheel-sdk

# Copy files and set permissions
COPY ./input/ ${FLYWHEEL}/input/
COPY ./src/ ${FLYWHEEL}/src/
COPY ./manifest.json ${FLYWHEEL}/
COPY ./run_pipeline.sh ${FLYWHEEL}/
RUN chmod +x ${FLYWHEEL}/run_pipeline.sh ${FLYWHEEL}/src/pipeline_scripts/* && \
    chmod -R 755 ${FLYWHEEL}

# Configure entrypoint
ENTRYPOINT ["/bin/bash", "/flywheel/v0/run_pipeline.sh"]
